### ISSUE TITLE
Make GNOME Terminal theme generator for themer

### ISSUE THREAD

**Issue by agarrharr** [agarrharr/themer-gnome-terminal#1]
https://github.com/mjswensen/themer#create-your-own-template

**Comment by agarrharr** [comment]
@mjswensen I'm having some trouble getting this to work. I'm not entirely sure how themer works.

First, my tests are failing, when I run `npm start`.

Second, I'm trying to figure out how to try it out without first publishing to npm.

I tried running `npm link` so that I can hopefully use `themer-gnome-terminal` globally, and then I tried:

```sh
themer -c themer-colors-default themer-gnome-terminal -o gen/
```

But it said `Please provide at least one template to render`.

I also tried

```sh
themer -c themer-colors-default ./lib/install.sh -o gen/
```

And it has the same response.

**Comment by mjswensen** [comment]
You are close. You are missing the `-t` (`--template`) flag. Also, rather than using `npm link` probably the easiest way to do it is simply reference the directory's path directly, like so:

    themer -c themer-colors-default -t /path/to/themer-gnome-terminal -o gen/

**Comment by agarrharr** [comment]
Nice!

Now, I'm much closer. Now it's just saying

```
resolving packages...
rendering templates...
TypeError: template.render is not a function
```

**Comment by mjswensen** [comment]
OK, cool, almost there. Make sure your render function is being exported from your module. ES6:

    export const render = ...

Or without babel, Common-JS:

    module.exports = {
      render: ...
    };

**Comment by agarrharr** [comment]
Yep! https://github.com/agarrharr/themer-gnome-terminal/blob/master/src/index.js#L14

**Comment by agarrharr** [comment]
I actually get the same error when I try using `themer-terminal`:

```sh
~/Development/themer-terminal master*❯ themer -c themer-colors-default -t . -o gen/
resolving packages...
rendering templates...
TypeError: template.render is not a function
```

**Comment by mjswensen** [comment]
Ah I see what's going on. To be honest, https://github.com/mjswensen/themer-terminal is not a great starting point as it is needlessly complicated (it has to make a call to a Swift script to generate the file in a special Apple format, and is also therefore macOS-only). I would probably look at https://github.com/mjswensen/themer-alfred instead. `themer-alfred` takes the color params from `themer` and returns a simple text file that `themer` writes. (Most of the themer packages work this way, `themer-terminal` is an exception.) That's how I envision `themer-gnome-terminal` to work, returning your customized shell script that users will run to install their theme.

**Comment by agarrharr** [comment]
Awesome. That helps.

**Comment by agarrharr** [comment]
@mjswensen Alright, I've got it done! Thanks for all your help!
